# Will override root ncurc.yml
# @link https://github.com/raineorshine/npm-check-updates

reject: [
    # Ignore package direct deps for npm-check-updates. That way we declare a less
    # restrictive range if the consuming app lock its deps to exact versions
    '@emotion/react',
    '@emotion/styled',
    'react',
    'react-dom',
    # Till mdx2 is well supported in react 18
    # - https://github.com/mdx-js/mdx/issues/1945
    # - https://github.com/storybookjs/storybook/issues/18094
    '@mdx-js/react',
  ]
